# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6867031ecc4766cc3873e0325b185a32449253ad9339fac93a7b6bb5b1fae9d30d3f2b91fd10618cde9abefafdd6b50c2d7dd9694964e34f01b9f00e6189e1

test:
  secret_key_base: 20b569065576727a65116765ddaf8aef75098b460b58bc79e1df5ccb5b6f8085c58ccfae0a4075b6a309164ead91e53b6540a0b3c42de0ecf9148b9e87aa72d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
